### PR TITLE
fmp4: add muxer for fragmented MP4's.

### PR DESCRIPTION
**Pull request by RealKeyboardWarrior**
Important note: filtetype must end in fmp4 to be recognized as fragmented mp4. This can be improved.

feature:      FragmentedMP4: added a muxer to create fragmented MP4's
docs:          FragmentedMP4: example was added that converts MP4 to fMP4
bug: 	  TrackFragHeader: fix missing TrackId not being encoded
bug: 	  TrackFragDecodeTime: decode time was not properly encoded
bug: 	  ElemStreamDesc: faulty length calculation (3 addition bytes  ESID + ESFlags) caused broken audio

### CODE REVIEW

**Comment by pystub** [comment]
I think you can reduce the requirement to construct an `fmp4.Muxer` to only need `io.Writer`

**Comment by RealKeyboardWarrior** [comment]
@pystub that is 100% correct. It does not seek anymore, I discovered that a few days ago.
But I need to check the interfaces to be sure that it will match with the Muxer interface.

**Comment by pystub** [comment]
Well FLV and TS muxers only require an `io.Writer` as well. Also these are just functions, so there's no need for interfaces to be compatible.

**Comment by cedricve** [comment]
Looking good! thank you @RealKeyboardWarrior

**Pull request merged**
